title: "SKILLSPHERE" 
description: "A platform to exchange skills locally. "
baseurl: "/sb1-nrlooe"
url: "https://mohanraj1408.github.io" 
theme: jekyll-theme-minimal 
markdown: kramdown 
plugins:
  - jekyll-seo-tag 
  - jekyll-sitemap
